security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        GescomBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        db_provider:
            entity:
                class: GescomBundle:User
                property: username

    access_control:
        # - { path: ^/mon-compte/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/mon-compte/connexion$
            anonymous: true

        main:
            pattern: ^/
            anonymous: true
            provider: db_provider

            form_login:
                login_path: login
                check_path: login_check

            logout:
                path: logout
                target: /mon-compte
