<?php

namespace GescomBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $email
     * @param $password
     * @return mixed
     */
    public function loadUserByUsername($email, $password)
    {
        return $this->createQueryBuilder('u')
            ->where('u.email = :email AND u.password = :password')
            ->setParameter('username', $email)
            ->setParameter('email', $password)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
